@echo off
rem DEVTOOL_WRAPPER_LAUNCHER=1
rem Generated by `devtool wrapper init/update`. Do not edit by hand.
setlocal
set "DEVTOOL_REPO_ROOT=%~dp0"
if "%DEVTOOL_REPO_ROOT:~-1%"=="\" set "DEVTOOL_REPO_ROOT=%DEVTOOL_REPO_ROOT:~0,-1%"
devtool --repo "%DEVTOOL_REPO_ROOT%" wrapper exec %*
exit /b %ERRORLEVEL%
