.TH "ARC-UPDATE" "1" "2026-09-27" "arc-cli" "Arc Manual"
.SH "NAME"
arc\-update \- update archive members
.SH "SYNOPSIS"
arc update ARCHIVE INPUT... [OPTIONS]
.PP
arcu ...
.PP
arc\-update ...
.SH "DESCRIPTION"
Update existing members or add changed inputs where the selected backend and format support normalized update semantics.
.SH "EXAMPLES"
arcu files.7z changed/
.SH "SEE ALSO"
arc\-create(1), arc\-add(1), arc\-remove(1)
