.TH "ARC-ADD" "1" "2026-09-27" "arc-cli" "Arc Manual"
.SH "NAME"
arc\-add \- add new archive members
.SH "SYNOPSIS"
arc add ARCHIVE INPUT... [OPTIONS]
.PP
arca ...
.PP
arc\-add ...
.SH "DESCRIPTION"
Add new archive members under Arc's normalized input/filter/backend policy. Existing member names are conflicts; use update when replacement is intended.
.SH "EXAMPLES"
arca files.zip new.txt
.SH "SEE ALSO"
arc\-create(1), arc\-update(1), arc\-remove(1)
